version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:buster
    environment:
        BUILD_IMAGE: italia/publiccode-editor-build
        FINAL_IMAGE: italia/publiccode-editor
    steps:
      - checkout
      - setup_remote_docker

      - run: echo $DOCKER_PASSWORD | docker login --username italia --password-stdin

      # Build the image with development tools and push it to Dockerhub
      - run: docker build --target build-stage -t $BUILD_IMAGE:$CIRCLE_SHA1 .
      - run: docker push $BUILD_IMAGE:$CIRCLE_SHA1

      # Build the final image
      - run: docker build -t $FINAL_IMAGE:$CIRCLE_SHA1 .
      - run: docker push $FINAL_IMAGE:$CIRCLE_SHA1

  test:
    docker:
        - image: italia/publiccode-editor-build:${CIRCLE_SHA1}
    working_directory: /app
    steps:
      - run: yarn lint
      - run: yarn test

  deploy:
    docker:
      - image: circleci/buildpack-deps:buster
    environment:
        FINAL_IMAGE: italia/publiccode-editor
    steps:
      - setup_remote_docker

      # Install rsync if it's not installed
      - run: which rsync || sudo apt-get update && sudo apt-get install -y rsync

      - run: echo "export CONTAINER_ID=$(docker create --rm $FINAL_IMAGE:$CIRCLE_SHA1)" >> $BASH_ENV
      - run: docker cp $CONTAINER_ID:/usr/share/nginx/html/. /tmp/html

      # Add to known hosts
      - run: mkdir -p ~/.ssh
      - run: echo $SSH_KNOWN_HOSTS | base64 -d >> ~/.ssh/known_hosts

      # rsync the files to the production machine
      - run: rsync --delete -avP --rsync-path="sudo -u www-data rsync" /tmp/html/ circleci@developers.italia.it:/apps/www/publiccode-editor.developers.italia.it/web/

workflows:
  version: 2
  continuous-deploy:
    jobs:
      - build

      - test:
          requires:
            - build

      - deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - build
