on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  publiccode_validation:
    runs-on: ubuntu-latest
    steps:
    - id: pcvalidation
      uses: actions/publiccode-parser-action
      with:
        publiccode: 'publiccode.yml'
    - name: Get the output time
      run: echo "Validation ${{ steps.pcvalidation.outputs.validation }}"
